- name: "{{ item.name }} - Private key [RSA 2048]"
  openssl_privatekey:
    path: "{{ allspark_root_directory }}/data/secrets/haproxy/private_keys/{{ item.host }}.key"
    type: RSA
    size: 2048
  register: priv

- name: "{{ item.name }} - CSR"
  openssl_csr:
    path: "{{ allspark_root_directory }}/data/secrets/haproxy/csrs/{{ item.host }}.csr"
    privatekey_path: "{{ allspark_root_directory }}/data/secrets/haproxy/private_keys/{{ item.host }}.key"
    common_name: "{{ item.host }}"
    country_name: "{{ allspark_haproxy.selfsigned.country }}"
    state_or_province_name: "{{ allspark_haproxy.selfsigned.state }}"
    locality_name: "{{ allspark_haproxy.selfsigned.location }}"
    organization_name: "{{ allspark_haproxy.selfsigned.organisation }}"
    organizational_unit_name: "{{ allspark_haproxy.selfsigned.organizational_unit }}"
    subject_alt_name: "DNS:{{ item.host }}"
    key_usage:
    - keyAgreement
    - keyEncipherment
    - digitalSignature
    - nonRepudiation
  register: csr

- name: "{{ item.name }} Certificate status"
  stat: path="{{ allspark_root_directory}}/data/ssl/certificates/{{ item.host }}.crt"
  changed_when: false
  register: crt_file

- name: "{{ item.name }} Certificate"
  shell: >-
    openssl x509 -req \
      -in {{ allspark_root_directory }}/data/secrets/haproxy/csrs/{{ item.host }}.csr \
      -CA {{ allspark_root_directory }}/data/ssl/certificates/ca.crt \
      -CAkey {{ allspark_root_directory }}/data/secrets/haproxy/private_keys/ca.key \
      -CAcreateserial \
      -out {{ allspark_root_directory }}/data/ssl/certificates/{{ item.host }}.crt \
      -days 1825 \
      -sha256
  when: not crt_file.stat.exists or priv is changed or csr is changed
  register: cert

- name: "{{ item.name }} Combined certificate status"
  stat: path="{{ allspark_root_directory}}/data/secrets/haproxy/certificates/{{ item.host }}.combined.pem"
  changed_when: false
  register: combined_file

- name: "{{ item.name }} Combined certificate"
  shell: >-
    cat
    {{ allspark_root_directory }}/data/secrets/haproxy/private_keys/{{ item.host }}.key
    {{ allspark_root_directory}}/data/ssl/certificates/{{ item.host }}.crt
    {{ allspark_root_directory }}/data/ssl/certificates/ca.crt
    > {{ allspark_root_directory}}/data/secrets/haproxy/certificates/{{ item.host }}.combined.pem
  when: not combined_file.stat.exists or priv is changed or cert is changed
