language: python
python:
- '3.7.0'
install:
- pip install --upgrade pip
jobs:
  include:
  - stage: deploy
    script: bash .travis/deploy_docs.sh
    env:
    - ENCRYPTION_LABEL: 00dec0d56e73
    - COMMIT_AUTHOR_EMAIL: "germain.gau@gmail.com"
    on:
      branch: develop
