- name: Run using a project directory
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - defaults/main.yml
  tasks:
  - name: Setup software infrastructure
    include_role:
      name: infra

  - name: Setup Monitoring
    include_role:
      name: monitoring
    when: allspark_monitoring.enabled

  - name: Setup Gitlab
    include_role:
      name: gitlab
    when: allspark_gitlab.enabled
