- name: Run using a project directory
  hosts: all
  tasks:
  - name: Setup software infrastructure
    include_role:
      name: infra

  - name: Setup Monitoring
    include_role:
      name: monitoring

  - name: Setup Gitlab
    include_role:
      name: gitlab

  - name: Setup Jenkins
    include_role:
      name: jenkins
