- name: Importing admin password
  shell: "cat {{ allspark_root_directory}}/data/secrets/admin_password.txt"
  register: admin_password
  changed_when: False

- name: Creating users volume
  docker_volume:
    name: "allspark_{{ item }}"
  with_items:
    - ldap_data
    - ldap_config

- name: Starting LDAP server
  docker_container:
    name: ldap_authentication
    hostname: ldap_authentication
    image: "{{ allspark_ldap.image }}"
    networks:
      - name: allspark
    env:
      LDAP_ADMIN_PASSWORD: "{{ admin_password.stdout }}"
      LDAP_DOMAIN: "{{ allspark_root_domain }}"
    volumes:
      - allspark_ldap_data:/var/lib/ldap
      - allspark_ldap_config:/etc/ldap

- name: Starting LDAP web management dashboard
  docker_container:
    name: ldap_management
    image: "{{ allspark_ldap.management_image }}"
    networks:
      - name: allspark
    env:
      PHPLDAPADMIN_LDAP_HOSTS: ldap_authentication
      PHPLDAPADMIN_HTTPS: false
    labels:
      "traefik.backend": "ldap_management"
      "traefik.frontend.rule": "Host:users.{{ allspark_root_domain }}"
      "traefik.enable": "true"
