version: 2

# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/ansible-lint.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/ansible-lint.tar | true
      - run:
          name: Build ansible-lint Docker image
          command: |
            docker build --cache-from=ansible-lint -t yokogawa/ansible-lint .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/ansible-lint.tar yokogawa/ansible-lint
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/ansible-lint.tar
      - run:
          name: Run ansible-lint (test)
          command: |
            docker run -it --rm yokogawa/ansible-lint ansible-lint --version
      # use docker cloud/hub
      #- deploy:
      #    name: Push application Docker image
      #    command: |
      #      if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #        login="$(aws ecr get-login)"
      #        ${login}
      #        docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #        docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #      fi
  create-pull-request:
    working_directory: /app/docker-ansible-lint
    docker:
      - image: golang
    steps:
      - checkout
      - run:
          name: setup command
          command: |
            curl -sL https://github.com/github/hub/releases/download/v2.2.9/hub-linux-amd64-2.2.9.tgz | tar xz -C /usr/local/bin --strip-components=2 -f - hub-linux-amd64-2.2.9/bin/hub
            apt-get update && apt-get -y install jq
      - add_ssh_keys:
          fingerprints:
            - "59:35:d6:58:31:87:ac:e6:f2:87:f3:0e:9e:8d:c2:e1"
      - run:
          name: compare tags
          command: |
            for tag in $(curl -sL https://api.github.com/repos/willthames/ansible-lint/tags | jq -r ".[].name"); do
              case ${tag} in
                v3.2.*) :;;
                v3.3.*) :;;
                v3.4.?rc*) :;;
                v3.4.?) :;;
                v3.4.1?) :;;
                *rc*)
                  if [[ $(git tag -l ${tag}) ]]; then
                    :
                  else
                    export ANSIBLE_VERSION=${tag#v}
                    export GIT_COMMITTER_NAME=yokogawa-k
                    export GIT_COMMITTER_EMAIL="${GIT_COMMITTER_NAME}@klab.com"
                    export GIT_AUTHOR_NAME=${GIT_COMMITTER_NAME}
                    export GIT_AUTHOR_EMAIL="${GIT_COMMITTER_NAME}@klab.com"
                    sed -i -e "s/ENV VERSION .*/ENV VERSION ${ANSIBLE_VERSION}/" Dockerfile
                    git checkout -b update_${ANSIBLE_VERSION}
                    git add Dockerfile
                    git commit -m "Update version to ${ANSIBLE_VERSION}"
                    git tag ${tag}
                    git push origin ${tag}
                  fi
                  ;;
                *)
                  if [[ $(git tag -l ${tag}) ]]; then
                    :
                  else
                    export ANSIBLE_VERSION=${tag#v}
                    export GIT_COMMITTER_NAME=yokogawa-k
                    export GIT_COMMITTER_EMAIL="${GIT_COMMITTER_NAME}@klab.com"
                    export GIT_AUTHOR_NAME=${GIT_COMMITTER_NAME}
                    export GIT_AUTHOR_EMAIL="${GIT_COMMITTER_NAME}@klab.com"
                    sed -i -e "s/ENV VERSION .*/ENV VERSION ${ANSIBLE_VERSION}/" Dockerfile
                    git checkout -b update_${ANSIBLE_VERSION}
                    git add Dockerfile
                    git commit -m "Update version to ${ANSIBLE_VERSION}"
                    git push origin update_${ANSIBLE_VERSION}
                    git tag ${tag}
                    git push origin ${tag}
                    # pull-request from yokogawa-k-bot
                    export GITHUB_USER=yokogawa-k-bot
                    hub pull-request -m "$(git log -1 --pretty=%B)"
                    git checkout master
                  fi
                  ;;
              esac
            done
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "20 * * * *"
          filters:
            branches:
              only: master
    jobs:
      - create-pull-request

