- name: allspark data directory creation
  file:
    state: directory
    path: "{{ allspark_root_directory }}/{{item}}"
  with_items:
    - config
    - data
    - data/secrets

- name: send [Pip] Requirements to remote server
  copy:
    src: files/requirements.txt
    dest: "{{ allspark_root_directory }}/config/pip-requirements.txt" 

- name: Installing python libraries using requirements file in Ansible
  pip:
    requirements: "{{ allspark_root_directory }}/config/pip-requirements.txt"
  become: true
