- name: allspark_root_directory creation
  file:
    state: directory
    path: "{{ allspark_root_directory }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0740
  become: yes

- name: allspark data/config directory creation
  file:
    state: directory
    path: "{{ allspark_root_directory }}/{{item}}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0740
  with_items:
    - config
    - data

- name: allspark secrets directory creation
  file:
    state: directory
    path: "{{ allspark_root_directory }}/{{item}}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0700
  with_items:
    - data/secrets

- name: send [Pip] Requirements to remote server
  copy:
    src: files/requirements.txt
    dest: "{{ allspark_root_directory }}/config/pip-requirements.txt"

- name: Installing python libraries using requirements file
  pip:
    requirements: "{{ allspark_root_directory }}/config/pip-requirements.txt"
    extra_args: --user
