---

- name: Get docker volume list
  shell: docker volume ls | grep -i allspark | awk '{print $2}'
  register: volumes_list

- name: Verify Docker volumes
  docker_volume:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ volumes_list.stdout_lines }}"

- name: Get docker name list
  shell: docker ps -q --filter label=managedby=allspark | xargs -n 1 docker inspect --format \{\{' .Name '\}\} | sed 's/\// /' | tr -d '\r\n'
  register: names_list

- name: Starting creating Backup container
  docker_container:
    name: backup
    image: "{{ allspark_backup.image }}"
    volumes: >-
      [
      {% for volume in volumes_list.stdout_lines %}
      "{{ volume }}:/source/{{ volume }}:ro",
      {% endfor %}
      "/var/run/docker.sock:/var/run/docker.sock",
      "{{ allspark_backup_directory }}:/backup",
      ]
    env:
      VOLUMERIZE_SOURCE: '/source'
      VOLUMERIZE_TARGET: 'file:///backup'
      VOLUMERIZE_CONTAINERS: "{{ names_list.stdout }}"
    restart_policy: always

- name: Launch Restore task
  shell: docker exec backup restore
  tags: restore

- name: Launch Restore task
  shell: docker exec backup restore --dry-run
  tags: dry-run

