<<<<<<< HEAD
<<<<<<< HEAD
- name: yum - EPEL repository enabled ?
  stat: path={{ allspark_epel_repo_file }}
  register: repo

- block:
  - name: import EPEL GPG key
    rpm_key:
      key: "{{ allspark_epel_gpg_url }}"
      state: present
    become: yes

  - name: install EPEL repository
    yum:
      name: "{{ allspark_epel_repo_url }}"
      state: present
    become: yes
  when: not repo.stat.exists

- name: "Install {{ ansible_distribution }} prerequisite for docker"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2 
    - python-pip
    state: present
  become: yes

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: Ensure old versions of Docker are not installed. | CentOS
=======
- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} - Ensure old versions of Docker are not installed"
>>>>>>> 6c48f47... Update Sys Playbook
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine
    - docker-selinux
    - docker-client
    - docker-client-latest
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine-selinux
=======
---


- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} - Install Storage Drivers for docker"
  yum:
    name: device-mapper-persistent-data
    state: present
>>>>>>> 84ac31e... Update System Playbook
  become: yes

