- include_tasks: "{{ prerequisites_file }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}.yml"
  loop_control:
    loop_var: prerequisites_file

- name: Docker - Ensuring daemon is started
  service: state=started name=docker
  become: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '14'

- name: Docker - Ensuring daemon is started
  systemd: state=started name=docker
  become: true
  when: ansible_distribution == 'Centos' or ansible_distribution == 'RedHat'

- name: FS - Ensuring Allspark directory
  file:
    path: "{{ allspark_root_directory }}"
    state: "directory"
  become: true

- name: FS - Ensuring Allspark directory owner
  file:
    path: "{{ allspark_root_directory }}"
    owner: "{{ ansible_user }}"
  become: true
