---


- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Install Specific OS Family dependency"
  include_tasks:
    - "{{ ansible_os_family }}.yml"

- name: Docker - Ensuring daemon is started
  service: state=started name=docker
  become: true
  when: systemd_is_not_present is true

- name: Docker - Ensuring daemon is started
  systemd: state=started name=docker
  become: true
  when: systemd_is_not_present is false

- name: FS - Ensuring Allspark directory
  file:
    path: "{{ allspark_root_directory }}"
    state: "directory"
  become: true

- name: FS - Ensuring Allspark directory owner
  file:
    path: "{{ allspark_root_directory }}"
    owner: "{{ ansible_user }}"
  become: true
