- name: yum - EPEL repository enabled ?
  stat: path={{ allspark_epel_repo_file }}
  register: repo

- block:
  - name: import EPEL GPG key
    rpm_key:
      key: "{{ allspark_epel_gpg_url }}"
      state: present
    become: yes

  - name: install EPEL repository
    yum:
      name: "{{ allspark_epel_repo_url }}"
      state: present
    become: yes
  when: not repo.stat.exists

- name: "Install {{ ansible_distribution }} prerequisite for docker"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - python-pip
    state: present
  become: yes
  
- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: Ensure old versions of Docker are not installed. | RedHat
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine
    - docker-selinux
    - docker-client
    - docker-client-latest
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine-selinux
  become: yes

- name: Install [Docker]
  yum:
    name: "docker-ce-{{ allspark_docker_version }}*"
    state: present
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: yes
  register: user_task

# - name: Reset ssh connection
#   meta: reset_connection
#   when: user_task is changed
#   failed_when: false

# Below is an ugly hack, because of an issue with
# `meta: reset_connection`:
## ERROR! Cannot reset connection
## b'Control socket connect(/home/$USER/.ansible/cp/276d6f8b70): No such file or directory\r\n'
#
# So we use this trick to force ansible to reconnect
- name: Remove cp dir to force ssh reconnection.
  file:
    path: ~/.ansible/cp
    state: absent
  delegate_to: localhost
  changed_when: false
  when: user_task is changed
