<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> c0a8e27... Add specific RedHat Playbook
- name: yum - EPEL repository enabled ?
  stat: path={{ allspark_epel_repo_file }}
  register: repo

- block:
  - name: import EPEL GPG key
    rpm_key:
      key: "{{ allspark_epel_gpg_url }}"
      state: present
<<<<<<< HEAD
    become: yes
=======
    become: true
>>>>>>> c0a8e27... Add specific RedHat Playbook

  - name: install EPEL repository
    yum:
      name: "{{ allspark_epel_repo_url }}"
      state: present
<<<<<<< HEAD
    become: yes
  when: not repo.stat.exists

- name: "Install {{ ansible_distribution }} prerequisite for docker"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2 
    - python-pip
    state: present
  become: yes
  
=======
    become: true
  when: not repo.stat.exists

- name: Install yum utils
  yum:
    name: yum-utils
    state: latest
  become: true

- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: latest
  become: true

- name: Install lvm2
  yum:
    name: lvm2
    state: latest
  become: true

>>>>>>> c0a8e27... Add specific RedHat Playbook
- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

<<<<<<< HEAD
=======
>>>>>>> 6c48f47... Update Sys Playbook
- name: Ensure old versions of Docker are not installed. | RedHat
  package:
    name: "{{ item }}"
=======
- name: Ensure old versions of Docker are not installed. | RedHat
  package:
    name: '{{ item }}'
>>>>>>> c0a8e27... Add specific RedHat Playbook
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine
    - docker-selinux
<<<<<<< HEAD
    - docker-client
    - docker-client-latest
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine-selinux
=======
---


# You can found all RedHat presreauisite on the docker official website : https://docs.docker.com/install/linux/docker-ee/rhel/#prerequisites

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} - Install Storage Drivers for docker"
  yum:
    name: overlay2
    state: present
>>>>>>> 84ac31e... Update System Playbook
  become: yes

=======
  when: ansible_os_family == 'RedHat'
  become: true

- name: test pip install
  shell: which pip
  failed_when: false
  changed_when: false
  register: pip_install

- name: Install pip
  shell: "curl https://bootstrap.pypa.io/get-pip.py | python -"
  become: true
  when: pip_install.rc != 0

- name: test docker install
  shell: which docker
  changed_when: false
  failed_when: false
  register: docker_install

- name: Install [Docker]
  yum:
    name: "docker-ce-{{ allspark_docker_version }}*"
  become: true
  when: docker_install.rc != 0

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true
  register: user_task

- name: Remove cp dir to force ssh reconnection.
  file:
    path: ~/.ansible/cp
    state: absent
  delegate_to: localhost
  changed_when: false
  when: user_task is changed
>>>>>>> c0a8e27... Add specific RedHat Playbook
