---

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD

# You can found this list on the docker official website : https://docs.docker.com/install/linux/docker-ce/ubuntu/

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Ensure Storages dependencies are installed"
  apt:
    name: "{{ linuximage }}"
    state: present
    update_cache: yes
  vars:
    linuximage:
    - "linux-image-extra-{{ ansible_kernel }}"
    - linux-image-extra-virtual
  become: yes

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Add Docker apt key"
  apt_key:
    url: "{{ allspark_ubuntu_docker_url }}"
    state: present
  register: add_repository_key
  ignore_errors: true
  become: yes

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Standard Add repo Failed - install curl to use alternative method"
  package:
    name: curl
    state: present
  become: yes
  when: add_repository_key is failed

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Add Docker apt key (alternative for older systems without SNI)"
  shell: "curl -sSL {{ allspark_ubuntu_docker_url }} | sudo apt-key add -"
  args:
    warn: no
  when: add_repository_key is failed
  become: yes

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Add Docker repository"
  apt_repository:
    repo: "deb [arch=amd64] {{ allspark_ubuntu_repo }} {{ ansible_distribution_release }} stable"
    state: present
  become: yes
<<<<<<< HEAD
=======
- name: Ensure old versions of Docker are not installed
=======
- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} - Ensure old versions of Docker are not installed"
>>>>>>> 6c48f47... Update Sys Playbook
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io
  become: true
=======
>>>>>>> 84ac31e... Update System Playbook

# You can found this list on the docker official website : https://docs.docker.com/install/linux/docker-ce/ubuntu/

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Ensure Storages dependencies are installed"
  apt:
    name: "{{ linuximage }}"
    state: present
<<<<<<< HEAD
    update-cache: yes
  with_items:
      - "linux-image-extra-{{ ansible_kernel }}"
      - linux-image-extra-virtual
<<<<<<< HEAD
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python-pip
  become: true

- name: Update pip
  pip:
    name: pip
    extra_args: -U
  become: true

- name: "Add Docker apt key for {{ ansible_distribution }}-{{ ansible_distribution_version }} {{ ansible_distribution_release }}"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true
  become: true

- name: Ensure curl is present (on older systems without SNI).
  package: name=curl state=present
  when: add_repository_key is failed
  become: true

- name: Add Docker apt key (alternative for older systems without SNI).
  shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  args:
    warn: no
  when: add_repository_key is failed
  become: true

- name: Add Docker repository.
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  become: true

- name: Install [Docker]
  apt:
    pkg: "docker-ce={{ allspark_docker_version }}*"
    state: present
    update_cache: yes
  become: true

- name: Start Docker service
  service:
    name: docker
    state: restarted
    enabled: yes
  become: true

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  register: user_task
  become: true

# - name: Reset ssh connection
#   meta: reset_connection
#   when: user_task is changed
#   failed_when: false

# Below is an ugly hack, because of an issue with
# `meta: reset_connection`:
## ERROR! Cannot reset connection
## b'Control socket connect(/home/$USER/.ansible/cp/276d6f8b70): No such file or directory\r\n'
#
# So we use this trick to force ansible to reconnect
- name: Remove cp dir to force ssh reconnection.
  file:
    path: ~/.ansible/cp
    state: absent
  delegate_to: localhost
  changed_when: false
  when: user_task is changed
>>>>>>> 02c5ac2... Create Ubuntu 14.04 Playbook

=======
>>>>>>> 6c48f47... Update Sys Playbook
=======
    update_cache: yes
  vars:
    linuximage:
    - "linux-image-extra-{{ ansible_kernel }}"
    - linux-image-extra-virtual
  become: yes
>>>>>>> 7fe2af1... Update System Playbook
=======

>>>>>>> 98d8990... Update from review
