---


# You can found this list on the docker official website : https://docs.docker.com/install/linux/docker-ce/ubuntu/

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Ensure Storages dependencies are installed"
  apt:
    name: "{{ item }}"
    state: present
    update-cache: yes
  with_items:
      - "linux-image-extra-{{ ansible_kernel }}"
      - linux-image-extra-virtual
