---

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} - Ensure old versions of Docker are not installed"
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io
  become: true

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Ensure dependencies are installed"
  apt:
    name: "{{ item }}"
    state: present
    update-cache: yes
  with_items:
      - "linux-image-extra-{{ ansible_kernel }}"
      - linux-image-extra-virtual
