- name: Docker network creation
  docker_network:
    name: "allspark"

- name: Create traefik config folder
  file:
    state: directory
    path: "{{ allspark_root_directory }}/config/traefik"

- name: Create traefik data certs folder
  file:
    state: directory
    path: "{{ allspark_root_directory }}/data/secrets/traefik/certs/"
  when: allspark_traefik.selfsigned

- name: Create traefik data private folder
  file:
    state: directory
    path: "{{ allspark_root_directory }}/data/secrets/traefik/certs/private"
  when: allspark_traefik.selfsigned

- name: Generate an OpenSSL private key with an algorithm DSA with size 2048
  openssl_privatekey:
    path: "{{ allspark_root_directory }}/data/secrets/traefik/certs/private/traefik.pem"
    type: RSA
    size: 2048
    force: true
  when: allspark_traefik.selfsigned

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: "{{ allspark_root_directory }}/data/secrets/traefik/certs/traefik.csr"
    privatekey_path: "{{ allspark_root_directory }}/data/secrets/traefik/certs/private/traefik.pem"
    country_name: "{{ allspark_country }}"
    state_or_province_name: "{{ allspark_state }}"
    locality_name: "{{ allspark_location }}"
    organization_name: "{{ allspark_organisation }}"
    common_name: "{{ allspark_common_name }}"
    organizational_unit_name: "{{ organizational_unit }}"
    force: true
  when: allspark_traefik.selfsigned

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{ allspark_root_directory }}/data/secrets/traefik/certs/traefik.crt"
    privatekey_path: "{{ allspark_root_directory }}/data/secrets/traefik/certs/private/traefik.pem"
    csr_path: "{{ allspark_root_directory }}/data/secrets/traefik/certs/traefik.csr"
    provider: selfsigned
    force: true
  when: allspark_traefik.selfsigned

- name: Prepare Traefik configuration
  template:
    src: templates/traefik.toml.j2
    dest: "{{ allspark_root_directory }}/config/traefik/traefik.toml"

- name: Setup ingress manager
  docker_container:
    name: traefik
    image: "{{ allspark_traefik.image }}"
    volumes: >-
      [
      "{{ allspark_root_directory }}/config/traefik/traefik.toml:/etc/traefik/traefik.toml",
      "/var/run/docker.sock:/var/run/docker.sock",
        {% if allspark_traefik.selfsigned %}
        "{{ allspark_root_directory }}/data/secrets/traefik/certs/traefik.crt:/certs/traefik.crt",
        "{{ allspark_root_directory }}/data/secrets/traefik/certs/traefik.pem:/certs/traefik.pem",
        {% endif %}
      ]
    ports: >-
      [
      "80:80",
      {% if allspark_traefik.selfsigned %}
      "443:443",
      {% endif %}
      ]
    networks:
      - name: allspark
    labels:
      "traefik.backend": "traefik"
      "traefik.port": "8080"
      "traefik.frontend.rule": "Host:ingress.{{ allspark_root_domain }}"
      "traefik.enable": "true"
    restart_policy: always
