---

- name: Starting SMTP Relay
  docker_container:
    name: smtp_relay
    image: "{{ downloads.smtp.image }}:{{ downloads.smtp.tag }}"
    purge_networks: true
    env: >-
      {
        {% if allspark_smtp.generic.enabled -%}
        "SMARTHOST_ADDRESS":"{{ allspark_smtp.generic.address }}",
        "SMARTHOST_PORT":"{{ allspark_smtp.generic.port }}",
        "SMARTHOST_ALIASES":"{{ allspark_smtp.generic.aliases }}",
        {%- elif allspark_smtp.gmail.enabled -%}
        "GMAIL_USER":"{{ allspark_smtp.gmail.user }}",
        "GMAIL_PASSWORD":"{{ allspark_smtp.gmail.password }}",
        {%- elif allspark_smtp.amazon_ses.enabled -%}
        "SES_USER":"{{ allspark_smtp.amazon_ses.user }}",
        "SES_PASSWORD":"{{ allspark_smtp.amazon_ses_password }}",
        "SES_REGION":"{{ allspark_smtp.amazon_ses.region }}",
        "SES_PORT":"{{ allspark_smtp.amazon_ses.port }}",
        {%- endif -%}
      }
    networks:
      - name: allspark
    labels:
      "heritage": "allspark"
    restart_policy: always
  when: allspark_smtp.enabled
