---

- name: Create traefik data certs folder
  file:
    state: directory
    path: "{{ allspark_root_directory }}/data/traefik/certs"

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=FR/ST=Haute-Garonne/L=Toulouse/O=CRE/CN=${ansible_fqdn}" -days 3650 -keyout "{{ allspark_root_directory }}/data/traefik/certs/traefik.key" -out "{{ allspark_root_directory }}/data/traefik/certs/traefik.crt"
  creates: "{{ allspark_root_directory }}/data/traefik/certs/traefik.crt"
