---

- name: Starting SMTP Relay
  docker_container:
    name: smtp_relay
    image: "{{ downloads.smtp.image }}:{{ downloads.smtp.tag }}"
    purge_networks: true
    environment:
      - SMARTHOST_ADDRESS="{{ allspark_smtp_address }}"
      - SMARTHOST_PORT="{{ allspark_smtp_port }}"
    networks:
      - name: allspark
    labels:
      "heritage": "allspark"
    restart_policy: always
